#ifndef __RTTHREAD_CFG_H__
#define __RTTHREAD_CFG_H__

#define RT_ALIGN_SIZE 4
#define RT_NAME_MAX 8

#define RT_THREAD_STACK_SIZE 512

#define RT_THREAD_PRIORITY_MAX 32

#define RT_USING_SEMAPHORE
#define RT_USING_MUTEX
#define RT_USING_EVENT
#define RT_USING_MAILBOX
#define RT_USING_MESSAGEQUEUE
#define RT_USING_MEMHEAP
#define RT_USING_MEMPOOL
#define RT_USING_DEVICE
#define RT_USING_MODULE

#endif /* __RTTHREAD_CFG_H__ */
